-- AlterEnum
ALTER TYPE "ExpenseCategory" ADD VALUE 'AUTO_LOAN';
ALTER TYPE "ExpenseCategory" ADD VALUE 'AUTO_INSURANCE';
ALTER TYPE "ExpenseCategory" ADD VALUE 'CREDIT_CARD';
ALTER TYPE "ExpenseCategory" ADD VALUE 'MEDICAL';
ALTER TYPE "ExpenseCategory" ADD VALUE 'PHONE';
ALTER TYPE "ExpenseCategory" ADD VALUE 'STUDENT_LOAN';
ALTER TYPE "ExpenseCategory" ADD VALUE 'LIFE_INSURANCE';
ALTER TYPE "ExpenseCategory" ADD VALUE 'SUBSCRIPTIONS';
